name: Main workflow

on:
  pull_request:
  push:
  schedule:
    - cron: '55 12 * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run unit tests
        run: |
          cargo build -vv --all --release
          cargo test






